-- Query 1 (Inserts synthetic data into "PUBLISHERS" table)

INSERT INTO publishers
(publisher_name, country, email)
VALUES
('Penguin Books', 'United Kingdom', 'info@penguin.com'),
('Oxford Press', 'United Kingdom', 'info@oxford.com'),
('HarperCollins', 'United States', 'info@harpercollins.com'),
('Random House', 'United States', 'info@randomhouse.com'),
('Macmillan Publishers', 'United Kingdom', 'info@macmillan.com'),
('Simon & Schuster', 'United States', 'info@simonandschuster.com'),
('Pearson', 'United Kingdom', 'info@pearson.com'),
('Cambridge University Press', 'United Kingdom', 'info@cambridge.org'),
('Springer', 'Germany', 'info@springer.com'),
('Wiley', 'United States', 'info@wiley.com'),
('Hachette Book Group', 'United States', 'info@hachettebookgroup.com'),
('Scholastic', 'United States', 'info@scholastic.com'),
('Bloomsbury Publishing', 'United Kingdom', 'info@bloomsbury.com'),
('Faber and Faber', 'United Kingdom', 'info@faber.co.uk'),
('Canongate Books', 'United Kingdom', 'info@canongate.co.uk'),
('Vintage Books', 'United States', 'info@vintagebooks.com'),
('Doubleday', 'United States', 'info@doubleday.com'),
('Bantam Books', 'United States', 'info@bantam.com'),
('Knopf Publishing', 'United States', 'info@knopf.com'),
('Little, Brown and Company', 'United States', 'info@littlebrown.com'),
('Tor Books', 'United States', 'info@tor.com'),
('Orbit Books', 'United Kingdom', 'info@orbit-books.co.uk'),
('Pan Macmillan', 'United Kingdom', 'info@panmacmillan.com'),
('Routledge', 'United Kingdom', 'info@routledge.com'),
('Taylor & Francis', 'United Kingdom', 'info@tandf.co.uk'),
('Elsevier', 'Netherlands', 'info@elsevier.com'),
('Pearson Education', 'United States', 'info@pearsoned.com'),
('McGraw Hill', 'United States', 'info@mcgrawhill.com'),
('Cengage Learning', 'United States', 'info@cengage.com'),
('W. W. Norton & Company', 'United States', 'info@wwnorton.com'),
('Princeton University Press', 'United States', 'info@press.princeton.edu'),
('Harvard University Press', 'United States', 'info@harvardpress.edu'),
('Yale University Press', 'United States', 'info@yaleupress.edu'),
('Stanford University Press', 'United States', 'info@sup.org'),
('MIT Press', 'United States', 'info@mitpress.mit.edu'),
('University of Chicago Press', 'United States', 'info@press.uchicago.edu'),
('Columbia University Press', 'United States', 'info@cup.columbia.edu'),
('Duke University Press', 'United States', 'info@dukeupress.edu'),
('Princeton Academic Press', 'United States', 'info@princetonacademic.com'),
('Cornell University Press', 'United States', 'info@cornellpress.cornell.edu'),
('University of California Press', 'United States', 'info@ucpress.edu'),
('Grove Atlantic', 'United States', 'info@groveatlantic.com'),
('Riverhead Books', 'United States', 'info@riverheadbooks.com'),
('Farrar Straus and Giroux', 'United States', 'info@fsgbooks.com'),
('Alfred A. Knopf', 'United States', 'info@aknopf.com'),
('St. Martin''s Press', 'United States', 'info@stmartins.com'),
('Grand Central Publishing', 'United States', 'info@grandcentralpublishing.com'),
('Crown Publishing Group', 'United States', 'info@crownpublishing.com'),
('Ballantine Books', 'United States', 'info@ballantinebooks.com'),
('Dell Publishing', 'United States', 'info@dellpublishing.com'),
('Avon Books', 'United States', 'info@avonbooks.com'),
('Ace Books', 'United States', 'info@acebooks.com'),
('Berkley Books', 'United States', 'info@berkleybooks.com'),
('DAW Books', 'United States', 'info@dawbooks.com'),
('Baen Books', 'United States', 'info@baen.com'),
('Del Rey Books', 'United States', 'info@delreybooks.com'),
('Schirmer Books', 'United States', 'info@schirmerbooks.com'),
('Kensington Books', 'United States', 'info@kensingtonbooks.com'),
('Sourcebooks', 'United States', 'info@sourcebooks.com'),
('Workman Publishing', 'United States', 'info@workman.com'),
('Abrams Books', 'United States', 'info@abramsbooks.com'),
('Chronicle Books', 'United States', 'info@chroniclebooks.com'),
('Ten Speed Press', 'United States', 'info@tenspeed.com'),
('Beacon Press', 'United States', 'info@beacon.org'),
('The New Press', 'United States', 'info@thenewpress.com'),
('Basic Books', 'United States', 'info@basicbooks.com'),
('PublicAffairs', 'United States', 'info@publicaffairsbooks.com'),
('Free Press', 'United States', 'info@freepress.com'),
('Scribner', 'United States', 'info@scribnerbooks.com'),
('Atria Books', 'United States', 'info@atriabooks.com'),
('Gallery Books', 'United States', 'info@gallerybooks.com'),
('Pocket Books', 'United States', 'info@pocketbooks.com'),
('Fawcett Books', 'United States', 'info@fawcettbooks.com'),
('Henry Holt and Company', 'United States', 'info@henryholt.com'),
('Metropolitan Books', 'United States', 'info@metropolitanbooks.com'),
('Picador', 'United States', 'info@picador.com'),
('Farrar Straus Giroux', 'United States', 'info@fsgbooks.com'),
('Europa Editions', 'United States', 'info@europaeditions.com'),
('Graywolf Press', 'United States', 'info@graywolfpress.org'),
('Milkweed Editions', 'United States', 'info@milkweed.org'),
('Copper Canyon Press', 'United States', 'info@coppercanyonpress.org'),
('City Lights Publishers', 'United States', 'info@citylights.com'),
('New Directions Publishing', 'United States', 'info@ndbooks.com'),
('Coffee House Press', 'United States', 'info@coffeehousepress.org'),
('Graydon House', 'United States', 'info@graydonhouse.com'),
('William Morrow', 'United States', 'info@williammorrow.com'),
('William Collins', 'United Kingdom', 'info@williamcollinsbooks.com'),
('Collins Publishers', 'United Kingdom', 'info@collins.co.uk'),
('Hodder & Stoughton', 'United Kingdom', 'info@hodder.co.uk'),
('Headline Publishing Group', 'United Kingdom', 'info@headline.co.uk'),
('Transworld Publishers', 'United Kingdom', 'info@transworldbooks.co.uk'),
('Constable & Robinson', 'United Kingdom', 'info@constablerobinson.com'),
('Harvill Secker', 'United Kingdom', 'info@harvillsecker.co.uk'),
('Jonathan Cape', 'United Kingdom', 'info@jonathancape.co.uk'),
('Chatto & Windus', 'United Kingdom', 'info@chattoandwindus.co.uk'),
('Heinemann', 'United Kingdom', 'info@heinemann.com'),
('Methuen Publishing', 'United Kingdom', 'info@methuen.com'),
('Faber Academic', 'United Kingdom', 'info@faberacademic.co.uk'),
('Duckworth Books', 'United Kingdom', 'info@duckworthbooks.com'),
('Profile Books', 'United Kingdom', 'info@profilebooks.com'),
('Verso Books', 'United Kingdom', 'info@versobooks.com'),
('Polity Press', 'United Kingdom', 'info@politybooks.com'),
('Sage Publications', 'United Kingdom', 'info@sagepub.co.uk'),
('Emerald Publishing', 'United Kingdom', 'info@emerald.com'),
('Kogan Page', 'United Kingdom', 'info@koganpage.com'),
('Jessica Kingsley Publishers', 'United Kingdom', 'info@jkp.com'),
('David & Charles', 'United Kingdom', 'info@davidandcharles.com');