-- Query 1 (Inserts synthetic data into "CATEGORIES" table)

INSERT INTO categories
(category_name, description)
VALUES
('Fiction', 'General fictional literature'),
('Classic Literature', 'Classic literary works'),
('Science Fiction', 'Science and futuristic fiction'),
('Fantasy', 'Fantasy and magical stories'),
('Mystery', 'Mystery and detective stories'),
('Romance', 'Romantic literature'),
('History', 'Historical books'),
('Biography', 'Biographical works'),
('Philosophy', 'Philosophical works'),
('Technology', 'Technology and computing'),
('Adventure', 'Adventure and exploration stories'),
('Horror', 'Horror and supernatural fiction'),
('Thriller', 'Suspenseful thriller novels'),
('Crime', 'Crime and criminal investigations'),
('Drama', 'Dramatic literary works'),
('Poetry', 'Poetry and poetic collections'),
('Short Stories', 'Collections of short fictional stories'),
('Essays', 'Essay collections and literary essays'),
('Young Adult', 'Literature intended for young adults'),
('Children', 'Books written for children'),
('Historical Fiction', 'Fiction set in historical periods'),
('Contemporary Fiction', 'Modern fictional literature'),
('Literary Fiction', 'Character and theme focused fiction'),
('Dystopian', 'Dystopian societies and futures'),
('Utopian', 'Idealized societies and worlds'),
('Steampunk', 'Steampunk technology and adventure'),
('Cyberpunk', 'Technology driven futuristic fiction'),
('Space Opera', 'Epic stories set in space'),
('Time Travel', 'Stories involving time travel'),
('Paranormal', 'Supernatural and paranormal stories'),
('Mythology', 'Myths legends and ancient traditions'),
('Folklore', 'Traditional stories and folk culture'),
('Fairy Tales', 'Traditional and modern fairy tales'),
('Legends', 'Legendary and heroic stories'),
('Comics', 'Comic books and graphic literature'),
('Graphic Novels', 'Long form graphic storytelling'),
('Manga', 'Japanese style graphic literature'),
('Education', 'Educational and instructional books'),
('Textbooks', 'Academic textbooks and course materials'),
('Reference', 'Reference and information resources'),
('Encyclopedias', 'Comprehensive reference works'),
('Dictionaries', 'Language dictionaries and word references'),
('Science', 'General scientific literature'),
('Physics', 'Physics and physical sciences'),
('Chemistry', 'Chemistry and chemical sciences'),
('Biology', 'Biology and life sciences'),
('Astronomy', 'Astronomy and space science'),
('Mathematics', 'Mathematics and mathematical theory'),
('Medicine', 'Medical and healthcare literature'),
('Psychology', 'Psychology and behavioral sciences'),
('Sociology', 'Society and social sciences'),
('Anthropology', 'Anthropology and human cultures'),
('Economics', 'Economic theory and practice'),
('Business', 'Business management and commerce'),
('Finance', 'Finance banking and investment'),
('Accounting', 'Accounting and financial reporting'),
('Marketing', 'Marketing advertising and branding'),
('Management', 'Business and organizational management'),
('Leadership', 'Leadership and organizational development'),
('Law', 'Legal studies and law'),
('Politics', 'Political science and government'),
('International Relations', 'International politics and diplomacy'),
('Geography', 'Geographical studies and places'),
('Environment', 'Environmental studies and sustainability'),
('Ecology', 'Ecology and natural ecosystems'),
('Nature', 'Nature wildlife and natural environments'),
('Agriculture', 'Agriculture and farming'),
('Engineering', 'Engineering and technical studies'),
('Computer Science', 'Computer science and programming'),
('Software Development', 'Software engineering and development'),
('Artificial Intelligence', 'Artificial intelligence and machine learning'),
('Data Science', 'Data analysis and data science'),
('Cybersecurity', 'Cybersecurity and information protection'),
('Networking', 'Computer networks and communications'),
('Web Development', 'Web technologies and development'),
('Databases', 'Database systems and data management'),
('Architecture', 'Architecture and building design'),
('Art', 'Visual arts and artistic studies'),
('Photography', 'Photography techniques and history'),
('Music', 'Music theory history and performance'),
('Film', 'Film studies and cinema'),
('Theater', 'Theater drama and stage performance'),
('Dance', 'Dance performance and choreography'),
('Cooking', 'Cooking recipes and culinary arts'),
('Food', 'Food culture and culinary studies'),
('Travel', 'Travel guides and travel literature'),
('Sports', 'Sports and athletic activities'),
('Fitness', 'Fitness exercise and physical training'),
('Self Help', 'Personal development and self improvement'),
('Health', 'General health and wellness'),
('Nutrition', 'Nutrition and healthy eating'),
('Parenting', 'Parenting and family guidance'),
('Religion', 'Religious studies and traditions'),
('Spirituality', 'Spiritual development and beliefs'),
('Ethics', 'Ethics and moral philosophy'),
('Linguistics', 'Language and linguistic studies'),
('Languages', 'Language learning and study'),
('Writing', 'Writing techniques and creative writing'),
('Journalism', 'Journalism and news writing'),
('Communication', 'Communication and interpersonal skills'),
('Crafts', 'Handicrafts and creative projects'),
('Gardening', 'Gardening and horticulture'),
('Reference Guides', 'Practical reference and guide books'),
('Memoir', 'Personal memoirs and life stories');